### ISSUE TITLE
Plugin Manager list of plugins is blank. (32 bit)

### ISSUE THREAD

**Issue by vulchor** [bruderstein/nppPluginManager#91] opened 2018-02-21 13:51 UTC
### Description of the Issue

Plugin manager list is blank.  I've reinstalled the plugin manager itself, but the list is still blank.
### Steps to Reproduce the Issue

1. Launch N++ as admin
2. Plugins -> Plugin Manager -> Show Plugins Manager
3. Blank list is displayed that says "No new plugins available" 

### Expected Behavior

Current list of available plugins to install
### Actual Behavior

"No new plugins available" 
### Debug Information

Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : combine.dll ComparePlugin.dll DSpellCheck.dll HexEditor.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

npp 1.4.9.0 (32-bit)

I had no trouble installing the Hex Editor plugin a couple of days ago.

**Comment by jamminjames** [comment] 2018-02-21 19:31
Same here!

**Comment by chcg** [comment] 2018-02-21 19:42
@vulchor Is this a reproducible issue or just a once issue? Do you use an admin account for updating? Do you have a direct internet connection or one behind a proxy (see #88).
You may want to switch under settings from the normal list to the devlist which should retrigger a new download otherwise N++ has to be restarted to allow a new list download.

**Comment by jamminjames** [comment] 2018-02-21 19:55
Thanks, the development list worked for me, but I never needed that before. If I try switching back to non-dev, no list again. Odd. Not behind a proxy, and it doesn't matter if I run Notepad as Admin or not.

**Comment by bruderstein** [comment] 2018-02-21 20:10
Should be fixed now. Was due to an error whilst moving servers around - apologies!

**Closed by bruderstein** 2018-02-21 20:10 UTC

**Comment by chcg** [comment] 2018-02-21 20:12
@bruderstein :-) Otherwise my answer would have been:

DevList shouldn't be necessary for your daily work as a normal user. But for me both lists are working fine for 32 and 64 bit. Could you try to download the list manually with IE/Edge from https://nppxml.bruderste.in/pm/xml/plugins.zip.

See also #86 about strange cookies, but that would affect all lists I think.

**Comment by jamminjames** [comment] 2018-02-21 20:37
Thanks, @bruderstein, all better now! (I did have to close Notepad++ and reopen, for anyone else experiencing this problem.)

**Comment by vulchor** [comment] 2018-02-22 10:05
Thanks, all good now.

**Comment by q2apro** [comment] 2018-12-15 19:41
Happens again: 

Notepad v7.5.9 (32 bit)

1. Launch N++ as admin
2. Plugins -> Plugin Manager -> Show Plugins Manager
3. Blank list is displayed that says "No new plugins available"

**Comment by patrickdrd** [comment] 2018-12-15 19:51
I'm running v7.6.1 portable and it doesn't work for me, "No new plugins available",
I actually deleted it because I thought that it was replaced by the new plugins admin,
what could I do?

**Comment by chcg** [comment] 2018-12-15 23:19
@patrickdrd Currently just the devlist is working. The content of the normal plugin list is broken on server side for 32bit and 64bit which just could be repaired by @bruderstein.
As you already run 7.6.1 PM is not yet fully adapted to support N++ 7.6 and newer.
You could download PM manually from https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.12. The PM dll needs to shifted manually to a created subdir PluginManager at
...\npp.7.6.1.bin.x64\plugins\PluginManager to be found by N++
